name: _build
on: 
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      runsOn:
        required: false
        type: string
        default: ubuntu-20.04

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v2 
      - name: docker build
        run: |
          docker-compose build ${{ inputs.component }}
