name: _build
on: 
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      runsOn:
        required: false
        type: string
        default: ubuntu-20.04

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: docker build
        working-directory: ${{ inputs.component }}/
        run: |
          pwd
          docker build -t ${{ inputs.component }} .
