on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - react-app/

jobs:
  build:
    uses: Implex1v/frontend-compare/.github/workflows/_build.yml@main
    with:
      component: react-app
